# account is "SA"
version: "3.7"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
    container_name: mssql
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: Y
      POSTGRES_DB: ank
      SA_PASSWORD: passw0rd 
    networks:
      - database
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - database
      
networks:
  database:
    driver: bridge