version: "3.7"
services:
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password ## Needed for adminer support
    # volumes:
    #   - /tmp/mysql:/var/lib/mysql
    ports:
      - "5432:5432/tcp"
      - "3306:3306/tcp"
      - "33060:33060/tcp"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd1234
      MYSQL_DATABASE: testbase
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    networks:
      - database

# Adminer wont work with mysql at the moment
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - database

networks:
  database:
    driver: bridge